### ISSUE TITLE
Exception ticking world I java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by TheButterbrotMan** [StrikerRockers-Mods/VanillaTweaksFabric#7]
https://pastebin.com/J8fTT0Vf

**Comment by strikerrocker** [comment]
This seems like an issue with immersive portal rather than VanillaTweaks.

**Comment by strikerrocker** [comment]
Create a issue here <https://github.com/qouteall/ImmersivePortalsMod/issues> with relevant information.
